apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron-container
              image: hussenali/node-get-matrices-03:v1
              volumeMounts:
                - name: data-pvc03
                  mountPath: /data
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
          volumes:
            - name: data-pvc03
              persistentVolumeClaim:
                claimName: data-pvc03